# Generated by Django 4.2 on 2023-04-24 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patchs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('checks', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('patch_name', models.CharField(max_length=100)),
                ('patch_no', models.CharField(max_length=100)),
                ('reference_url', models.URLField()),
            ],
            options={
                'db_table': 'patchlists',
            },
        ),
        migrations.CreateModel(
            name='Patchs_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patch_file', models.FileField(upload_to='')),
                ('patch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patch_list.patchs')),
            ],
            options={
                'db_table': 'patch_file',
            },
        ),
    ]
