# Generated by Django 4.2 on 2023-04-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patch_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patchs',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
